"use client";

import * as React from "react";
import { CheckCircle2, Download, FilePlus2, Save, Send } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { api, apiError } from "@/lib/api";
import { useAuthStore } from "@/store/auth";
import { PageHeader, EButton } from "@/components/eoc/page-header";
import { Surface, StatusPill, type Tone } from "@/components/eoc/primitives";
import { cn } from "@/lib/utils";

type Level = "green" | "amber" | "red";
type Item = { label:string; status:Level|"na"; findings:string; action:string };
type Section = { key:string; title:string; status:Level; summary:string; items:Item[] };
type Report = { _id:string; reportId:string; weekKey:string; name:string; status:"draft"|"in_review"|"published"; overallStatus:Level; executiveSummary:string; sections:Section[]; clientActions:string[]; generatedByName:string; updatedAt:string; publishedAt?:string; managedServiceValue?:{monthlyFee:number;currency:string;verifiedProviders:string[];monitoredResources:number;automatedChecks:string[];analystServices:string[];evidenceGeneratedAt:string} };
const tone:Record<string,Tone>={green:"success",amber:"warning",red:"danger",na:"neutral",draft:"neutral",in_review:"warning",published:"success"};

export default function MaintenanceReportsPage(){
  const qc=useQueryClient(); const canWrite=useAuthStore((s)=>s.can("reports:write"));
  const [selected,setSelected]=React.useState<string>(); const [editing,setEditing]=React.useState<Report>();
  const list=useQuery<Report[]>({queryKey:["maintenance-reports"],queryFn:async()=>{const {data}=await api.get("/maintenance-reports");return data.data;}});
  const reports=list.data||[]; const active=editing||reports.find((r)=>r._id===selected)||reports[0];
  React.useEffect(()=>{if(!selected&&reports[0])setSelected(reports[0]._id)},[reports,selected]);
  React.useEffect(()=>{const found=reports.find((r)=>r._id===selected);setEditing(found?structuredClone(found):undefined)},[selected,reports]);
  const create=useMutation({mutationFn:async()=>{const {data}=await api.post("/maintenance-reports/draft",{});return data.data as Report},onSuccess:(r)=>{qc.invalidateQueries({queryKey:["maintenance-reports"]});setSelected(r._id);toast.success("Weekly draft ready")},onError:(e)=>toast.error(apiError(e))});
  const save=useMutation({mutationFn:async(r:Report)=>{const {data}=await api.patch(`/maintenance-reports/${r._id}`,{overallStatus:r.overallStatus,executiveSummary:r.executiveSummary,clientActions:r.clientActions.filter(Boolean),sections:r.sections,status:"in_review"});return data.data},onSuccess:()=>{qc.invalidateQueries({queryKey:["maintenance-reports"]});toast.success("Report saved for review")},onError:(e)=>toast.error(apiError(e))});
  const publish=useMutation({mutationFn:async(id:string)=>{const {data}=await api.post(`/maintenance-reports/${id}/publish`);return data.data},onSuccess:()=>{qc.invalidateQueries({queryKey:["maintenance-reports"]});toast.success("Report published to the client")},onError:(e)=>toast.error(apiError(e))});
  const updateSection=(index:number,patch:Partial<Section>)=>setEditing((r)=>r?{...r,sections:r.sections.map((s,i)=>i===index?{...s,...patch}:s)}:r);
  const updateItem=(si:number,ii:number,patch:Partial<Item>)=>setEditing((r)=>r?{...r,sections:r.sections.map((s,i)=>i===si?{...s,items:s.items.map((item,j)=>j===ii?{...item,...patch}:item)}:s)}:r);
  const download=()=>{if(!active)return;const blob=new Blob([JSON.stringify(active,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${active.reportId}.json`;a.click();URL.revokeObjectURL(a.href)};
  return <div className="space-y-6">
    <PageHeader eyebrow="Service & governance" title="Maintenance Reports" description="Weekly managed-service evidence across applications, infrastructure, MongoDB, security, support and SLA governance." actions={<>{active&&<EButton variant="secondary" onClick={download}><Download/>Export evidence</EButton>}{active&&<EButton variant="secondary" onClick={()=>window.print()}><Download/>Print / PDF</EButton>}{canWrite&&<EButton variant="primary" disabled={create.isPending} onClick={()=>create.mutate()}><FilePlus2/>Prepare this week</EButton>}</>}/>
    <div className="grid gap-5 xl:grid-cols-[280px_1fr]">
      <Surface className="h-fit p-3"><p className="px-2 pb-2 text-xs font-semibold uppercase tracking-wider text-eoc-muted">Report archive</p>{list.isLoading?<p className="p-3 text-sm text-eoc-muted">Loading reports…</p>:reports.length===0?<p className="p-3 text-sm text-eoc-muted">No reports yet. An authorized manager can prepare this week&apos;s draft.</p>:<div className="space-y-1">{reports.map((r)=><button key={r._id} onClick={()=>setSelected(r._id)} className={cn("w-full rounded-xl p-3 text-left",active?._id===r._id?"bg-eoc-accent/10 ring-1 ring-eoc-accent/25":"hover:bg-slate-50")}><div className="flex items-center justify-between gap-2"><span className="text-sm font-medium text-eoc-fg">{r.weekKey}</span><StatusPill tone={tone[r.status]}>{r.status.replace("_"," ")}</StatusPill></div><p className="mt-1 text-xs text-eoc-muted">{r.reportId}</p></button>)}</div>}</Surface>
      {!active?<Surface className="p-10 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-eoc-muted"/><p className="mt-3 text-sm text-eoc-fg2">Your weekly reports will appear here.</p></Surface>:<Surface className="overflow-hidden">
        <div className="border-b border-eoc-border p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-lg font-semibold text-eoc-fg">{active.name}</p><p className="text-xs text-eoc-muted">{active.reportId} · Prepared by {active.generatedByName||"IAETDS"}</p></div><div className="flex gap-2"><StatusPill tone={tone[active.overallStatus]}>{active.overallStatus}</StatusPill><StatusPill tone={tone[active.status]}>{active.status.replace("_"," ")}</StatusPill></div></div>
        {canWrite&&active.status!=="published"?<><label className="mt-5 block text-xs font-medium text-eoc-fg2">Overall status</label><select value={active.overallStatus} onChange={(e)=>setEditing({...active,overallStatus:e.target.value as Level})} className="mt-1 rounded-lg border border-eoc-border bg-white px-3 py-2 text-sm"><option value="green">Green</option><option value="amber">Amber</option><option value="red">Red</option></select><label className="mt-4 block text-xs font-medium text-eoc-fg2">Executive summary</label><textarea value={active.executiveSummary} onChange={(e)=>setEditing({...active,executiveSummary:e.target.value})} rows={4} className="mt-1 w-full rounded-xl border border-eoc-border bg-white p-3 text-sm" placeholder="Summarize health, important changes, risks and client impact."/></>:<p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-eoc-fg2">{active.executiveSummary||"No executive summary supplied."}</p>}</div>
        {active.managedServiceValue&&<div className="mx-5 mt-5 rounded-xl border border-eoc-accent/25 bg-eoc-accent/5 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-eoc-accent">IAETDS Managed Service Value</p><h2 className="mt-1 text-lg font-semibold text-eoc-fg">₹{active.managedServiceValue.monthlyFee.toLocaleString("en-IN")} monthly coverage</h2></div><StatusPill tone={active.managedServiceValue.verifiedProviders.length?"success":"warning"}>{active.managedServiceValue.verifiedProviders.length} providers verified</StatusPill></div><div className="mt-4 grid gap-4 md:grid-cols-3"><div><p className="text-2xl font-semibold text-eoc-fg">{active.managedServiceValue.monitoredResources}</p><p className="text-xs text-eoc-muted">Discovered resources</p></div><div><p className="text-xs font-medium text-eoc-fg">Automated evidence</p><p className="mt-1 text-xs text-eoc-fg2">{active.managedServiceValue.automatedChecks.join(" · ")||"Awaiting verified provider connection"}</p></div><div><p className="text-xs font-medium text-eoc-fg">IAETDS service work</p><p className="mt-1 text-xs text-eoc-fg2">{active.managedServiceValue.analystServices.join(" · ")}</p></div></div></div>}
        <div className="space-y-4 p-5">{active.sections.map((s,si)=><details key={s.key} open={si===0} className="rounded-xl border border-eoc-border bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><span className="font-medium text-eoc-fg">File {si+1} — {s.title}</span><StatusPill tone={tone[s.status]}>{s.status}</StatusPill></summary><div className="border-t border-eoc-border p-4">{canWrite&&active.status!=="published"?<><select value={s.status} onChange={(e)=>updateSection(si,{status:e.target.value as Level})} className="rounded-lg border border-eoc-border bg-white px-3 py-2 text-sm"><option value="green">Green</option><option value="amber">Amber</option><option value="red">Red</option></select><textarea value={s.summary} onChange={(e)=>updateSection(si,{summary:e.target.value})} rows={3} className="mt-3 w-full rounded-xl border border-eoc-border p-3 text-sm" placeholder="Section summary"/></>:<p className="mb-4 whitespace-pre-wrap text-sm text-eoc-fg2">{s.summary||"No section summary supplied."}</p>}<div className="mt-4 space-y-2">{s.items.map((item,ii)=><div key={item.label} className="rounded-lg border border-eoc-border p-3"><div className="flex items-center justify-between gap-2"><span className="text-sm font-medium text-eoc-fg">{ii+1}. {item.label}</span>{canWrite&&active.status!=="published"?<select value={item.status} onChange={(e)=>updateItem(si,ii,{status:e.target.value as Item["status"]})} className="rounded-md border border-eoc-border bg-white px-2 py-1 text-xs"><option value="na">Not assessed</option><option value="green">Green</option><option value="amber">Amber</option><option value="red">Red</option></select>:<StatusPill tone={tone[item.status]}>{item.status}</StatusPill>}</div>{canWrite&&active.status!=="published"?<div className="mt-2 grid gap-2 md:grid-cols-2"><textarea value={item.findings} onChange={(e)=>updateItem(si,ii,{findings:e.target.value})} className="rounded-lg border border-eoc-border p-2 text-xs" placeholder="Findings / evidence"/><textarea value={item.action} onChange={(e)=>updateItem(si,ii,{action:e.target.value})} className="rounded-lg border border-eoc-border p-2 text-xs" placeholder="Action / recommendation"/></div>:<div className="mt-2 grid gap-2 text-xs text-eoc-fg2 md:grid-cols-2"><p><b>Findings:</b> {item.findings||"—"}</p><p><b>Action:</b> {item.action||"—"}</p></div>}</div>)}</div></div></details>)}</div>
        {canWrite&&active.status!=="published"&&<div className="flex flex-wrap justify-end gap-2 border-t border-eoc-border p-5"><EButton variant="secondary" disabled={save.isPending} onClick={()=>save.mutate(active)}><Save/>Save for review</EButton><EButton variant="primary" disabled={publish.isPending} onClick={()=>{if(confirm("Publish this report to client users? Published reports become read-only."))publish.mutate(active._id)}}><Send/>Publish to client</EButton></div>}
      </Surface>}
    </div>
  </div>
}
