"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Cloud, Database, ShieldAlert, Siren, Clock3, CheckCircle2, RefreshCw } from "lucide-react";
import { PageHeader, EButton } from "@/components/eoc/page-header";
import { StatusPill, Surface } from "@/components/eoc/primitives";
import { api } from "@/lib/api";
import { useDashboard } from "@/hooks/use-analytics";

type Point={timestamp:string;value:number}; type MetricData={available:boolean;units?:string;current?:number;average?:number;peak?:number;points?:Point[]}; type Telemetry={periodDays:number;fetchedAt:string;resources:{id:string|number;name:string;error?:string;metrics?:Record<string,MetricData>}[]};
type Connection={provider:"digitalocean"|"mongodb_atlas";status:string;lastCheckedAt?:string;lastSuccessfulAt?:string;lastError?:string;summary?:{dropletCount?:number;clusterCount?:number;droplets?:{id:number;name:string;status:string;region:string;size:string}[];clusters?:{name:string;stateName:string;mongoDBVersion:string;provider:string;region:string}[];telemetry?:Telemetry}};
export default function HealthPage(){
 const qc=useQueryClient(); const dashboard=useDashboard(); const connections=useQuery<Connection[]>({queryKey:["provider-connections"],queryFn:async()=>{const {data}=await api.get("/provider-connections");return data.data},refetchInterval:30000});
 const refresh=useMutation({mutationFn:()=>api.post("/provider-connections/telemetry/refresh"),onSuccess:()=>qc.invalidateQueries({queryKey:["provider-connections"]})});
 const values=connections.data||[],digitalOcean=values.find(c=>c.provider==="digitalocean"),atlas=values.find(c=>c.provider==="mongodb_atlas"),k=dashboard.data?.kpis;
 return <div className="space-y-6"><PageHeader eyebrow="30-day verified operational evidence" title="Health & Security" description="Monthly provider measurements and tenant security records. Unsupported metrics are shown as unavailable, never estimated." actions={<EButton variant="primary" disabled={refresh.isPending} onClick={()=>refresh.mutate()}><RefreshCw className={refresh.isPending?"animate-spin":""}/>Refresh 30 days</EButton>}/>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Siren} label="Critical incidents" value={k?.criticalIncidents||0}/><Metric icon={ShieldAlert} label="Open security findings" value={dashboard.data?.recentSecurity.length||0}/><Metric icon={Cloud} label="DigitalOcean Droplets" value={digitalOcean?.summary?.dropletCount||0}/><Metric icon={Database} label="Atlas clusters" value={atlas?.summary?.clusterCount||0}/></div>
 <Provider title="DigitalOcean infrastructure" icon={Cloud} connection={digitalOcean}>{digitalOcean?.summary?.droplets?.map(d=><Resource key={d.id} name={d.name} status={d.status} detail={[d.size,d.region].filter(Boolean).join(" · ")}/>)}</Provider><TelemetryPanel title="DigitalOcean · last 30 days" telemetry={digitalOcean?.summary?.telemetry}/>
 <Provider title="MongoDB Atlas database health" icon={Database} connection={atlas}>{atlas?.summary?.clusters?.map(c=><Resource key={c.name} name={c.name} status={c.stateName||"UNKNOWN"} detail={[c.provider,c.region,c.mongoDBVersion&&`MongoDB ${c.mongoDBVersion}`].filter(Boolean).join(" · ")}/>)}</Provider><TelemetryPanel title="MongoDB Atlas · last 30 days" telemetry={atlas?.summary?.telemetry}/>
 <Surface className="p-5"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 text-eoc-success"/><div><h2 className="font-semibold text-eoc-fg">Security boundary</h2><p className="mt-1 text-sm text-eoc-fg2">Provider service accounts are read-only and encrypted. Health checks use operational metadata; customer database documents are not read. Audit Logs record connection changes and tests.</p></div></div></Surface></div>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Cloud;label:string;value:number}){return <Surface className="p-5"><Icon className="h-5 w-5 text-eoc-accent"/><p className="mt-4 text-3xl font-semibold text-eoc-fg">{value}</p><p className="mt-1 text-sm text-eoc-muted">{label}</p></Surface>}
function Provider({title,icon:Icon,connection,children}:{title:string;icon:typeof Cloud;connection?:Connection;children:React.ReactNode}){return <Surface className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><Icon className="h-5 w-5 text-eoc-accent"/><div><h2 className="font-semibold text-eoc-fg">{title}</h2><p className="mt-1 flex items-center gap-1 text-xs text-eoc-muted"><Clock3 className="h-3.5 w-3.5"/>Last verified {connection?.lastSuccessfulAt?new Date(connection.lastSuccessfulAt).toLocaleString():"never"}</p></div></div><StatusPill tone={connection?.status==="connected"?"success":connection?.status==="error"?"danger":"neutral"}>{connection?.status||"Not connected"}</StatusPill></div>{connection?.lastError&&<p className="mt-3 text-sm text-eoc-danger">{connection.lastError}</p>}<div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{children||<p className="text-sm text-eoc-muted">No verified resources available. Test the connection first.</p>}</div></Surface>}
function Resource({name,status,detail}:{name:string;status:string;detail:string}){const good=["active","idle","available"].some(v=>status.toLowerCase().includes(v));return <div className="rounded-xl border border-eoc-border bg-slate-50 p-4"><div className="flex items-center justify-between gap-2"><p className="font-medium text-eoc-fg">{name}</p><StatusPill tone={good?"success":"warning"}>{status}</StatusPill></div><p className="mt-2 text-xs text-eoc-muted">{detail||"Provider metadata unavailable"}</p></div>}
function TelemetryPanel({title,telemetry}:{title:string;telemetry?:Telemetry}){return <Surface className="p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-eoc-fg">{title}</h2><p className="text-xs text-eoc-muted">{telemetry?.fetchedAt?`Fetched ${new Date(telemetry.fetchedAt).toLocaleString()}`:"Not fetched"}</p></div>{!telemetry?<p className="mt-4 text-sm text-eoc-muted">Press Refresh 30 days to retrieve provider measurements.</p>:<div className="mt-4 space-y-5">{telemetry.resources.map(r=><div key={r.id} className="rounded-xl border border-eoc-border p-4"><div className="flex items-center justify-between gap-2"><p className="font-medium text-eoc-fg">{r.name}</p><StatusPill tone={r.error?"warning":"success"}>{r.error?"Limited":"Monitoring active"}</StatusPill></div>{r.error?<p className="mt-2 text-sm text-eoc-danger">{r.error}</p>:<><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(r.metrics||{}).map(([name,m])=><div key={name} className="rounded-lg bg-slate-50 p-3"><p className="text-[11px] text-eoc-muted">{name.replaceAll("_"," ")}</p>{m.available?<><p className="mt-1 text-lg font-semibold text-eoc-fg">{formatMetric(m.current,m.units)}</p><p className="mt-1 text-[11px] text-eoc-muted">30-day avg {formatMetric(m.average,m.units)} · peak {formatMetric(m.peak,m.units)}</p></>:<p className="mt-1 text-sm text-eoc-muted">Unavailable</p>}</div>)}</div><MonthlyCalendar metrics={r.metrics||{}}/></>}</div>)}</div>}</Surface>}
function MonthlyCalendar({metrics}:{metrics:Record<string,MetricData>}){const now=new Date(),year=now.getFullYear(),month=now.getMonth(),days=new Date(year,month+1,0).getDate(),first=new Date(year,month,1).getDay();const evidence=new Set(Object.values(metrics).flatMap(m=>m.points||[]).map(p=>new Date(p.timestamp).toLocaleDateString("en-CA")));const today=now.toLocaleDateString("en-CA");const todayMetrics=Object.entries(metrics).map(([name,m])=>{const values=(m.points||[]).filter(p=>new Date(p.timestamp).toLocaleDateString("en-CA")===today).map(p=>p.value);return values.length?{name,peak:Math.max(...values),units:m.units}:null}).filter(Boolean) as {name:string;peak:number;units?:string}[];return <div className="mt-5 border-t border-eoc-border pt-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium text-eoc-fg">{now.toLocaleString(undefined,{month:"long",year:"numeric"})} monitoring calendar</p><p className="mt-1 text-xs text-eoc-muted">Green means provider evidence was captured for that day—not a guarantee that no risk existed.</p></div><div className="text-right"><p className="text-xs font-medium text-eoc-fg">Today&apos;s peaks</p><p className="mt-1 text-xs text-eoc-muted">{todayMetrics.length?todayMetrics.slice(0,3).map(m=>`${m.name.replaceAll("_"," ")}: ${formatMetric(m.peak,m.units)}`).join(" · "):"No measurements yet today"}</p></div></div><div className="mt-4 grid grid-cols-7 gap-1 text-center">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><span key={d} className="py-1 text-[10px] font-medium text-eoc-muted">{d}</span>)}{Array.from({length:first}).map((_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=new Date(year,month,i+1),key=date.toLocaleDateString("en-CA"),has=evidence.has(key),isToday=key===today;return <div key={key} className={`rounded-lg border p-2 ${isToday?"border-eoc-accent bg-eoc-accent/10":has?"border-green-200 bg-green-50":"border-eoc-border bg-slate-50"}`}><p className="text-xs font-semibold text-eoc-fg">{i+1}</p><p className={`mt-1 text-[9px] ${has?"text-green-700":"text-eoc-muted"}`}>{has?"Monitored":date>now?"Upcoming":"No data"}</p></div>})}</div></div>}
function formatMetric(value?:number,units=""){if(value==null||!Number.isFinite(value))return "—";const names:Record<string,string>={BYTES:"B",MEGABYTES:"MB",GIGABYTES:"GB",PERCENT:"%",SCALAR:""};return `${value.toLocaleString(undefined,{maximumFractionDigits:2})}${names[units]??` ${units}`}`}
