"use client";
import { useQuery } from "@tanstack/react-query";
import { Cloud, Database, ShieldAlert, Siren, Clock3, CheckCircle2 } from "lucide-react";
import { PageHeader } from "@/components/eoc/page-header";
import { StatusPill, Surface } from "@/components/eoc/primitives";
import { api } from "@/lib/api";
import { useDashboard } from "@/hooks/use-analytics";

type Connection={provider:"digitalocean"|"mongodb_atlas";status:string;lastCheckedAt?:string;lastSuccessfulAt?:string;lastError?:string;summary?:{dropletCount?:number;clusterCount?:number;droplets?:{id:number;name:string;status:string;region:string;size:string}[];clusters?:{name:string;stateName:string;mongoDBVersion:string;provider:string;region:string}[]}};
export default function HealthPage(){
 const dashboard=useDashboard(); const connections=useQuery<Connection[]>({queryKey:["provider-connections"],queryFn:async()=>{const {data}=await api.get("/provider-connections");return data.data},refetchInterval:30000});
 const values=connections.data||[],digitalOcean=values.find(c=>c.provider==="digitalocean"),atlas=values.find(c=>c.provider==="mongodb_atlas"),k=dashboard.data?.kpis;
 return <div className="space-y-6"><PageHeader eyebrow="Verified operational evidence" title="Health & Security" description="Live provider connection state and tenant security records. IAETDS does not inspect customer documents or store database passwords."/>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Siren} label="Critical incidents" value={k?.criticalIncidents||0}/><Metric icon={ShieldAlert} label="Open security findings" value={dashboard.data?.recentSecurity.length||0}/><Metric icon={Cloud} label="DigitalOcean Droplets" value={digitalOcean?.summary?.dropletCount||0}/><Metric icon={Database} label="Atlas clusters" value={atlas?.summary?.clusterCount||0}/></div>
 <Provider title="DigitalOcean infrastructure" icon={Cloud} connection={digitalOcean}>{digitalOcean?.summary?.droplets?.map(d=><Resource key={d.id} name={d.name} status={d.status} detail={[d.size,d.region].filter(Boolean).join(" · ")}/>)}</Provider>
 <Provider title="MongoDB Atlas database health" icon={Database} connection={atlas}>{atlas?.summary?.clusters?.map(c=><Resource key={c.name} name={c.name} status={c.stateName||"UNKNOWN"} detail={[c.provider,c.region,c.mongoDBVersion&&`MongoDB ${c.mongoDBVersion}`].filter(Boolean).join(" · ")}/>)}</Provider>
 <Surface className="p-5"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 text-eoc-success"/><div><h2 className="font-semibold text-eoc-fg">Security boundary</h2><p className="mt-1 text-sm text-eoc-fg2">Provider service accounts are read-only and encrypted. Health checks use operational metadata; customer database documents are not read. Audit Logs record connection changes and tests.</p></div></div></Surface></div>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Cloud;label:string;value:number}){return <Surface className="p-5"><Icon className="h-5 w-5 text-eoc-accent"/><p className="mt-4 text-3xl font-semibold text-eoc-fg">{value}</p><p className="mt-1 text-sm text-eoc-muted">{label}</p></Surface>}
function Provider({title,icon:Icon,connection,children}:{title:string;icon:typeof Cloud;connection?:Connection;children:React.ReactNode}){return <Surface className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><Icon className="h-5 w-5 text-eoc-accent"/><div><h2 className="font-semibold text-eoc-fg">{title}</h2><p className="mt-1 flex items-center gap-1 text-xs text-eoc-muted"><Clock3 className="h-3.5 w-3.5"/>Last verified {connection?.lastSuccessfulAt?new Date(connection.lastSuccessfulAt).toLocaleString():"never"}</p></div></div><StatusPill tone={connection?.status==="connected"?"success":connection?.status==="error"?"danger":"neutral"}>{connection?.status||"Not connected"}</StatusPill></div>{connection?.lastError&&<p className="mt-3 text-sm text-eoc-danger">{connection.lastError}</p>}<div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{children||<p className="text-sm text-eoc-muted">No verified resources available. Test the connection first.</p>}</div></Surface>}
function Resource({name,status,detail}:{name:string;status:string;detail:string}){const good=["active","idle","available"].some(v=>status.toLowerCase().includes(v));return <div className="rounded-xl border border-eoc-border bg-slate-50 p-4"><div className="flex items-center justify-between gap-2"><p className="font-medium text-eoc-fg">{name}</p><StatusPill tone={good?"success":"warning"}>{status}</StatusPill></div><p className="mt-2 text-xs text-eoc-muted">{detail||"Provider metadata unavailable"}</p></div>}
