"use client";
import * as React from "react";
import { Boxes, Plus, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, EButton } from "@/components/eoc/page-header";
import { EmptyState, StatusPill, Surface, type Tone } from "@/components/eoc/primitives";
import { Modal, Field, TextInput, SelectInput } from "@/components/eoc/modal";
import { useResourceList, useResourceMutation } from "@/hooks/use-resource";
import { apiError } from "@/lib/api";
import type { Asset } from "@/lib/types";
import { useAuthStore } from "@/store/auth";

const statusTone:Record<string,Tone>={operational:"success",degraded:"warning",maintenance:"warning",offline:"danger",retired:"neutral"};
const categories=["application","server","database","cloud","network","storage","endpoint","security_appliance","iot"];
const blank=()=>({name:"",assetTag:`AST-${Date.now().toString(36).toUpperCase()}`,category:"application",type:"",environment:"production",criticality:"medium",ipAddress:""});

export default function ApplicationsPage(){
  const accountOwner=useAuthStore((s)=>s.user?.name)||"Account owner";
  const [query,setQuery]=React.useState(""); const [open,setOpen]=React.useState(false); const [selected,setSelected]=React.useState<Asset>(); const [form,setForm]=React.useState(blank());
  const list=useResourceList<Asset>("assets",{limit:100,search:query}); const mutations=useResourceMutation("assets"); const assets=list.data?.data||[];
  const showAdd=()=>{setForm(blank());setOpen(true)};
  const add=async(e:React.FormEvent)=>{e.preventDefault();try{await mutations.create.mutateAsync({...form,status:"operational",healthScore:100});toast.success("Asset added to this workspace");setOpen(false)}catch(err){toast.error(apiError(err))}};
  const remove=async(a:Asset)=>{if(!confirm(`Remove ${a.name} from this workspace?`))return;try{await mutations.remove.mutateAsync(a._id);setSelected(undefined);toast.success("Asset removed")}catch(err){toast.error(apiError(err))}};
  return <div className="space-y-6">
    <PageHeader eyebrow="Tenant asset registry" title="Infrastructure & Applications" description="Only assets registered inside this client workspace appear here." actions={<EButton variant="primary" onClick={showAdd}><Plus/>Add asset</EButton>}/>
    <div className="flex h-10 items-center gap-2 rounded-xl border border-eoc-border bg-white px-3"><Search className="h-4 w-4 text-eoc-muted"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search this workspace…" className="flex-1 bg-transparent text-sm outline-none"/></div>
    {list.isLoading?<Surface className="p-10 text-center text-sm text-eoc-muted">Loading tenant assets…</Surface>:assets.length===0?<EmptyState icon={Boxes} title="No assets registered" description="This workspace starts empty. Add the client's first application, server, database, or cloud service." action={<EButton variant="primary" onClick={showAdd}><Plus/>Add first asset</EButton>}/>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{assets.map((a)=><button key={a._id} onClick={()=>setSelected(a)} className="text-left"><Surface hover className="h-full p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-eoc-fg">{a.name}</p><p className="mt-1 text-xs text-eoc-muted">{a.assetTag} · {a.category.replace("_"," ")}</p></div><StatusPill tone={statusTone[a.status]}>{a.status}</StatusPill></div><div className="mt-5 grid grid-cols-2 gap-3"><Fact label="Environment" value={a.environment}/><Fact label="Criticality" value={a.criticality}/><Fact label="Account owner" value={a.owner||accountOwner}/><Fact label="Health" value={`${a.healthScore}%`}/></div></Surface></button>)}</div>}
    <Modal open={open} onOpenChange={setOpen} title="Add tenant asset" description={`This asset will be owned by ${accountOwner}.`} width="max-w-2xl"><form onSubmit={add} className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Asset name"><TextInput required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} placeholder="AsliLearn Production API"/></Field><Field label="Asset ID"><TextInput required value={form.assetTag} onChange={(e)=>setForm({...form,assetTag:e.target.value})}/></Field><Field label="Category"><SelectInput value={form.category} onChange={(e)=>setForm({...form,category:e.target.value})}>{categories.map((x)=><option key={x} value={x}>{x.replace("_"," ")}</option>)}</SelectInput></Field><Field label="Type"><TextInput value={form.type} onChange={(e)=>setForm({...form,type:e.target.value})} placeholder="Node.js API, MongoDB Atlas…"/></Field><Field label="Environment"><SelectInput value={form.environment} onChange={(e)=>setForm({...form,environment:e.target.value})}><option value="production">Production</option><option value="staging">Staging</option><option value="development">Development</option><option value="dr">Disaster recovery</option></SelectInput></Field><Field label="Criticality"><SelectInput value={form.criticality} onChange={(e)=>setForm({...form,criticality:e.target.value})}><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></SelectInput></Field><Field label="Public URL or IP"><TextInput value={form.ipAddress} onChange={(e)=>setForm({...form,ipAddress:e.target.value})} placeholder="https://api.example.com"/></Field><div className="flex justify-end gap-2 sm:col-span-2"><EButton type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</EButton><EButton type="submit" variant="primary" disabled={mutations.create.isPending}>Add asset</EButton></div></form></Modal>
    <Modal open={!!selected} onOpenChange={(v)=>!v&&setSelected(undefined)} title={selected?.name||"Asset"} description="Tenant-scoped asset details">{selected&&<div className="space-y-4 p-5"><div className="grid grid-cols-2 gap-3"><Fact label="Asset ID" value={selected.assetTag}/><Fact label="Category" value={selected.category}/><Fact label="Environment" value={selected.environment}/><Fact label="Criticality" value={selected.criticality}/><Fact label="Account owner" value={selected.owner||accountOwner}/><Fact label="Address" value={selected.ipAddress||"Not supplied"}/></div><div className="flex justify-end"><EButton variant="danger" onClick={()=>remove(selected)}><Trash2/>Remove asset</EButton></div></div>}</Modal>
  </div>
}
function Fact({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-eoc-border bg-slate-50 p-3"><p className="text-[11px] text-eoc-muted">{label}</p><p className="mt-1 break-words text-sm font-medium capitalize text-eoc-fg">{value}</p></div>}
