"use client";
import * as React from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Cloud, Database, PlugZap, RefreshCw, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { api, apiError } from "@/lib/api";
import { PageHeader, EButton } from "@/components/eoc/page-header";
import { StatusPill, Surface } from "@/components/eoc/primitives";
import { Field, Modal, TextInput } from "@/components/eoc/modal";

type Provider="digitalocean"|"mongodb_atlas";
type Connection={provider:Provider;label:string;status:"configured"|"connected"|"error"|"disabled";lastCheckedAt?:string;lastSuccessfulAt?:string;lastError?:string;summary?:{dropletCount?:number;clusterCount?:number}};
const meta={digitalocean:{name:"DigitalOcean",description:"Read Droplets, infrastructure state and monitoring signals.",icon:Cloud},mongodb_atlas:{name:"MongoDB Atlas",description:"Read cluster health, operational metadata and observability signals.",icon:Database}};

export default function ConnectionsPage(){
 const qc=useQueryClient(); const [provider,setProvider]=React.useState<Provider>();
 const [form,setForm]=React.useState({label:"",token:"",projectId:"",clientId:"",clientSecret:""});
 const list=useQuery<Connection[]>({queryKey:["provider-connections"],queryFn:async()=>{const {data}=await api.get("/provider-connections");return data.data}});
 const save=useMutation({mutationFn:async()=>{const payload=provider==="digitalocean"?{provider,label:form.label,token:form.token}:{provider,label:form.label,projectId:form.projectId,clientId:form.clientId,clientSecret:form.clientSecret};const {data}=await api.post("/provider-connections",payload);return data.data},onSuccess:()=>{qc.invalidateQueries({queryKey:["provider-connections"]});setProvider(undefined);toast.success("Credentials encrypted and saved")},onError:(e)=>toast.error(apiError(e))});
 const test=useMutation({mutationFn:async(p:Provider)=>{const {data}=await api.post(`/provider-connections/${p}/test`);return data.data},onSuccess:()=>{qc.invalidateQueries({queryKey:["provider-connections"]});toast.success("Live provider connection verified")},onError:(e)=>{qc.invalidateQueries({queryKey:["provider-connections"]});toast.error(apiError(e))}});
 const remove=useMutation({mutationFn:async(p:Provider)=>api.delete(`/provider-connections/${p}`),onSuccess:()=>{qc.invalidateQueries({queryKey:["provider-connections"]});toast.success("Provider disconnected")},onError:(e)=>toast.error(apiError(e))});
 const open=(p:Provider)=>{setProvider(p);setForm({label:meta[p].name,token:"",projectId:"",clientId:"",clientSecret:""})};
 return <div className="space-y-6"><PageHeader eyebrow="Secure provider access" title="Connections" description="Connect client-owned services using dedicated read-only credentials. Secrets are encrypted and never shown after saving."/>
 <div className="grid gap-4 lg:grid-cols-2">{(["digitalocean","mongodb_atlas"] as Provider[]).map((p)=>{const M=meta[p],Icon=M.icon,c=list.data?.find(x=>x.provider===p);return <Surface key={p} className="p-5"><div className="flex items-start gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-eoc-accent/10"><Icon className="h-5 w-5 text-eoc-accent"/></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-eoc-fg">{M.name}</h2><StatusPill tone={c?.status==="connected"?"success":c?.status==="error"?"danger":"neutral"}>{c?.status||"Not connected"}</StatusPill></div><p className="mt-1 text-sm text-eoc-fg2">{M.description}</p>{c&&<div className="mt-4 rounded-xl border border-eoc-border bg-slate-50 p-3 text-xs text-eoc-fg2"><p>Last verified: {c.lastSuccessfulAt?new Date(c.lastSuccessfulAt).toLocaleString():"Not verified"}</p><p className="mt-1">Resources: {p==="digitalocean"?(c.summary?.dropletCount??0)+" Droplets":(c.summary?.clusterCount??0)+" clusters"}</p>{c.lastError&&<p className="mt-1 text-eoc-danger">{c.lastError}</p>}</div>}<div className="mt-4 flex flex-wrap gap-2">{!c?<EButton variant="primary" onClick={()=>open(p)}><PlugZap/>Connect</EButton>:<><EButton variant="secondary" onClick={()=>test.mutate(p)} disabled={test.isPending}><CheckCircle2/>Test connection</EButton><EButton variant="secondary" onClick={()=>open(p)}><RefreshCw/>Rotate credentials</EButton><EButton variant="danger" onClick={()=>confirm(`Disconnect ${M.name}?`)&&remove.mutate(p)}><Trash2/>Disconnect</EButton></>}</div></div></div></Surface>})}</div>
 <Surface className="p-5"><h2 className="font-semibold text-eoc-fg">Security model</h2><ul className="mt-3 space-y-2 text-sm text-eoc-fg2"><li>• Use dedicated read-only provider identities—never owner, root or database-user credentials.</li><li>• Credentials are encrypted at rest and excluded from every API response, log and report.</li><li>• Every configure, test, rotate and disconnect action is written to Audit Logs.</li></ul></Surface>
 <Modal open={!!provider} onOpenChange={(v)=>!v&&setProvider(undefined)} title={provider?`Connect ${meta[provider].name}`:"Connect provider"} description="Enter a dedicated read-only credential. It will not be displayed again."><form className="space-y-4 p-5" onSubmit={(e)=>{e.preventDefault();save.mutate()}}><Field label="Connection name"><TextInput required value={form.label} onChange={(e)=>setForm({...form,label:e.target.value})}/></Field>{provider==="digitalocean"?<Field label="Read-only API token"><TextInput required type="password" autoComplete="new-password" value={form.token} onChange={(e)=>setForm({...form,token:e.target.value})}/></Field>:<><Field label="Atlas Project ID"><TextInput required value={form.projectId} onChange={(e)=>setForm({...form,projectId:e.target.value})}/></Field><Field label="Service account client ID"><TextInput required value={form.clientId} onChange={(e)=>setForm({...form,clientId:e.target.value})}/></Field><Field label="Service account secret"><TextInput required type="password" autoComplete="new-password" value={form.clientSecret} onChange={(e)=>setForm({...form,clientSecret:e.target.value})}/></Field></>}<div className="flex justify-end gap-2"><EButton type="button" variant="secondary" onClick={()=>setProvider(undefined)}>Cancel</EButton><EButton type="submit" variant="primary" disabled={save.isPending}>Encrypt & save</EButton></div></form></Modal></div>
}
