"use client";
import Link from "next/link";
import { Activity, CheckCircle2, Cloud, Database, RefreshCw, Siren } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { PageHeader, EButton } from "@/components/eoc/page-header";
import { StatusPill, Surface, type Tone } from "@/components/eoc/primitives";
import { useResourceList } from "@/hooks/use-resource";
import { api } from "@/lib/api";
import type { Incident } from "@/lib/types";

type Connection={_id:string;provider:"digitalocean"|"mongodb_atlas";status:string;lastSuccessfulAt?:string;lastError?:string};
const severityTone:Record<string,Tone>={sev1:"danger",sev2:"warning",sev3:"info",sev4:"neutral"};

export default function IncidentsPage(){
 const qc=useQueryClient(),list=useResourceList<Incident>("incidents",{limit:100,sort:"-detectedAt"});
 const connections=useQuery<Connection[]>({queryKey:["provider-connections"],queryFn:async()=>{const {data}=await api.get("/provider-connections");return data.data}});
 const refresh=useMutation({mutationFn:()=>api.post("/provider-connections/telemetry/refresh",{month:new Date().toISOString().slice(0,7)}),onSuccess:()=>{qc.invalidateQueries({queryKey:["provider-connections"]});qc.invalidateQueries({queryKey:["incidents"]})}});
 const incidents=list.data?.data||[],providers=connections.data||[],connected=providers.filter(p=>p.status==="connected");
 const lastVerified=connected.map(p=>p.lastSuccessfulAt).filter(Boolean).sort().at(-1);
 return <div className="space-y-6">
  <PageHeader eyebrow="Production response" title="Incidents" description="Verified operational incidents and provider monitoring status for this workspace." actions={<EButton variant="primary" disabled={refresh.isPending||!connected.length} onClick={()=>refresh.mutate()}><RefreshCw className={refresh.isPending?"animate-spin":""}/>{refresh.isPending?"Checking…":"Check provider signals"}</EButton>}/>
  <div className="grid gap-4 md:grid-cols-3"><Summary icon={Siren} label="Open incidents" value={incidents.filter(i=>!["resolved","closed"].includes(i.status)).length.toString()} tone={incidents.some(i=>!["resolved","closed"].includes(i.status))?"warning":"success"}/><Summary icon={Activity} label="Monitoring coverage" value={`${connected.length} of 2 providers`} tone={connected.length===2?"success":"warning"}/><Summary icon={CheckCircle2} label="Last provider check" value={lastVerified?new Date(lastVerified).toLocaleString("en-IN"):"Not verified"} tone={lastVerified?"success":"neutral"}/></div>
  <Surface className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-eoc-fg">Signal sources</h2><p className="mt-1 text-xs text-eoc-muted">Only connected providers contribute verified operational evidence.</p></div><Link href="/console/connections" className="text-sm font-medium text-eoc-accent hover:underline">Manage connections</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2"><ProviderRow icon={Cloud} name="DigitalOcean" connection={providers.find(p=>p.provider==="digitalocean")}/><ProviderRow icon={Database} name="MongoDB Atlas" connection={providers.find(p=>p.provider==="mongodb_atlas")}/></div></Surface>
  {list.isLoading?<Surface className="p-10 text-center text-sm text-eoc-muted">Loading incidents…</Surface>:incidents.length===0?<Surface className="border-green-200 bg-green-50/60 p-10 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-green-600"/><h2 className="mt-4 font-semibold text-eoc-fg">No active production incidents</h2><p className="mx-auto mt-2 max-w-xl text-sm text-eoc-muted">No incident has been recorded for this workspace. This means no verified incident is currently open; it is not a guarantee that every possible risk has been eliminated.</p><div className="mt-5 flex justify-center gap-3"><Link href="/console/health" className="rounded-xl border border-eoc-border bg-white px-4 py-2 text-sm font-medium text-eoc-fg">View health evidence</Link><Link href="/console/connections" className="rounded-xl bg-eoc-accent px-4 py-2 text-sm font-medium text-white">Review connections</Link></div></Surface>:<div className="space-y-3">{incidents.map(i=><Surface key={i._id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-mono text-xs text-eoc-muted">{i.incidentId}</span><StatusPill tone={severityTone[i.severity]||"neutral"}>{i.severity.toUpperCase()}</StatusPill><StatusPill tone={i.status==="resolved"?"success":"warning"}>{i.status.replaceAll("_"," ")}</StatusPill></div><h2 className="mt-2 font-semibold text-eoc-fg">{i.title}</h2>{i.summary&&<p className="mt-1 text-sm text-eoc-fg2">{i.summary}</p>}</div><div className="text-right text-xs text-eoc-muted"><p>{new Date(i.detectedAt||i.createdAt||Date.now()).toLocaleString("en-IN")}</p><p className="mt-1">{i.category||"Operational"}</p></div></div>{i.rootCause&&<div className="mt-4 rounded-xl border border-eoc-border bg-slate-50 p-3"><p className="text-xs font-medium text-eoc-fg">Root cause</p><p className="mt-1 text-sm text-eoc-fg2">{i.rootCause}</p></div>}</Surface>)}</div>}
 </div>;
}
function Summary({icon:Icon,label,value,tone}:{icon:typeof Siren;label:string;value:string;tone:Tone}){return <Surface className="p-5"><div className="flex items-center justify-between"><Icon className="h-5 w-5 text-eoc-accent"/><StatusPill tone={tone}>{tone==="success"?"Healthy":tone==="warning"?"Attention":"Status"}</StatusPill></div><p className="mt-4 text-xl font-semibold text-eoc-fg">{value}</p><p className="mt-1 text-xs text-eoc-muted">{label}</p></Surface>}
function ProviderRow({icon:Icon,name,connection}:{icon:typeof Cloud;name:string;connection?:Connection}){const ok=connection?.status==="connected";return <div className="rounded-xl border border-eoc-border bg-slate-50 p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-eoc-accent"/><p className="text-sm font-medium text-eoc-fg">{name}</p></div><StatusPill tone={ok?"success":connection?.status==="error"?"danger":"neutral"}>{connection?.status||"Not connected"}</StatusPill></div><p className="mt-2 text-xs text-eoc-muted">{connection?.lastSuccessfulAt?`Last verified ${new Date(connection.lastSuccessfulAt).toLocaleString("en-IN")}`:"No successful verification yet"}</p>{connection?.lastError&&<p className="mt-2 text-xs text-eoc-danger">{connection.lastError}</p>}</div>}
