"use client";

import * as React from "react";
import { Activity, CheckCircle2, CircleDot, Cloud, Database, Download, GitCommitHorizontal, Play, RotateCcw, ShieldCheck, Sparkles, TimerReset, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, EButton } from "@/components/eoc/page-header";
import { SectionHeader, StatusPill, Surface, type Tone } from "@/components/eoc/primitives";
import { cn } from "@/lib/utils";

type Phase = "detected" | "investigating" | "awaiting_approval" | "remediating" | "verified";
const phases: { key: Phase; label: string }[] = [{ key: "detected", label: "Detected" }, { key: "investigating", label: "Investigated" }, { key: "awaiting_approval", label: "Approval" }, { key: "remediating", label: "Remediation" }, { key: "verified", label: "Verified" }];
const phaseIndex: Record<Phase, number> = { detected: 0, investigating: 1, awaiting_approval: 2, remediating: 3, verified: 4 };
const signals = [
  { source: "DigitalOcean", icon: Cloud, time: "10:42:08", title: "CPU saturation on api-prod-01", detail: "CPU reached 94% for 8 minutes; p95 latency increased to 1.84s.", tone: "warning" as Tone },
  { source: "MongoDB Atlas", icon: Database, time: "10:41:37", title: "Slow query rate increased 7.2×", detail: "orders.find aggregate is scanning 184k documents per request.", tone: "danger" as Tone },
  { source: "GitHub", icon: GitCommitHorizontal, time: "10:36:12", title: "Deployment checkout-api v2.14.0", detail: "Commit a91f0d2 changed the order lookup query and reached production.", tone: "info" as Tone },
];
const trail: Record<Phase, string[]> = {
  detected: ["10:42 · Three provider signals grouped into INC-1042"],
  investigating: ["10:42 · Three provider signals grouped into INC-1042", "10:43 · Dependency graph traced API latency to MongoDB query", "10:43 · Deployment diff identified as probable trigger (96% confidence)"],
  awaiting_approval: ["10:42 · Three provider signals grouped into INC-1042", "10:43 · Root cause identified across GitHub, DigitalOcean, and Atlas", "10:44 · Safe rollback plan generated; approval requested"],
  remediating: ["10:42 · Three provider signals grouped into INC-1042", "10:43 · Root cause identified across three providers", "10:44 · Priya approved production rollback", "10:44 · Rolling checkout-api back to v2.13.4"],
  verified: ["10:42 · Three provider signals grouped into INC-1042", "10:43 · Root cause identified across three providers", "10:44 · Priya approved production rollback", "10:45 · Rollback completed and health checks passed", "10:47 · p95 latency stable at 218ms; incident resolved"],
};

export default function IncidentWorkbenchPage() {
  const [phase, setPhase] = React.useState<Phase>("detected");
  const [busy, setBusy] = React.useState(false);
  const current = phaseIndex[phase];
  React.useEffect(() => { const saved = window.localStorage.getItem("iaetds-incident-demo-phase") as Phase | null; if (saved && saved in phaseIndex) setPhase(saved); }, []);
  const move = (next: Phase, message: string, delay = 700) => { setBusy(true); const id = toast.loading(message); window.setTimeout(() => { setPhase(next); window.localStorage.setItem("iaetds-incident-demo-phase", next); setBusy(false); toast.success(next === "verified" ? "Recovery verified" : "Workflow advanced", { id }); }, delay); };
  const reset = () => { setPhase("detected"); window.localStorage.setItem("iaetds-incident-demo-phase", "detected"); toast.success("Demo incident reset"); };
  const exportEvidence = () => {
    const report = { incident: "INC-1042", title: "Checkout latency and database saturation", severity: "SEV-1", status: phase, rootCause: "checkout-api v2.14.0 introduced an unindexed order lookup, causing Atlas document scans and DigitalOcean CPU saturation.", affectedProviders: ["DigitalOcean", "MongoDB Atlas", "GitHub"], remediation: "Approved rollback to checkout-api v2.13.4", verification: phase === "verified" ? { latencyBeforeMs: 1840, latencyAfterMs: 218, errorRateBefore: "8.7%", errorRateAfter: "0.2%", healthChecks: "passed" } : "pending", auditTrail: trail[phase], generatedAt: new Date().toISOString() };
    const url = URL.createObjectURL(new Blob([JSON.stringify(report, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "INC-1042-evidence.json"; link.click(); URL.revokeObjectURL(url); toast.success("Incident evidence exported");
  };
  return <div className="space-y-6">
    <PageHeader eyebrow="Cross-cloud incident response" title="Incident Workbench" description="Correlate signals across every provider, identify root cause, safely remediate with approval, and prove recovery." actions={<><EButton variant="secondary" onClick={reset}><TimerReset className="h-4 w-4" /> Reset demo</EButton><EButton variant="secondary" onClick={exportEvidence}><Download className="h-4 w-4" /> Export evidence</EButton></>} />
    <Surface className="overflow-hidden border-eoc-danger/30"><div className="flex flex-col gap-4 border-b border-eoc-border bg-eoc-danger/[0.05] p-5 lg:flex-row lg:items-center"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-eoc-danger/15"><TriangleAlert className="h-5 w-5 text-eoc-danger" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-xs text-eoc-muted">INC-1042</p><StatusPill tone="danger">SEV-1</StatusPill><StatusPill tone={phase === "verified" ? "success" : "warning"}>{phase.replace("_", " ")}</StatusPill></div><h2 className="mt-1 text-lg font-semibold text-eoc-fg">Checkout latency and database saturation</h2><p className="mt-1 text-sm text-eoc-fg2">Customer checkout is degraded across the production stack · detected 5 minutes ago</p></div><div className="flex gap-5 text-right text-sm"><div><p className="text-xs text-eoc-muted">Customers affected</p><p className="font-semibold text-eoc-fg">1,284</p></div><div><p className="text-xs text-eoc-muted">Revenue at risk</p><p className="font-semibold text-eoc-danger">₹2.4L/hr</p></div></div></div>
      <div className="grid grid-cols-5 p-4">{phases.map((p, i) => <div key={p.key} className="relative flex flex-col items-center gap-2 text-center"><div className={cn("absolute left-0 top-3 h-px w-full -translate-x-1/2", i === 0 && "hidden", i <= current ? "bg-eoc-success" : "bg-eoc-border")} /><span className={cn("relative z-10 flex h-6 w-6 items-center justify-center rounded-full border", i < current ? "border-eoc-success bg-eoc-success text-black" : i === current ? "border-eoc-accent bg-eoc-accent/20 text-eoc-accent" : "border-eoc-border bg-eoc-surface text-eoc-muted")}>{i < current ? <CheckCircle2 className="h-3.5 w-3.5" /> : <span className="text-[10px]">{i + 1}</span>}</span><span className="text-[10px] text-eoc-muted sm:text-xs">{p.label}</span></div>)}</div></Surface>
    <div className="grid gap-4 xl:grid-cols-3"><Surface className="p-5 xl:col-span-2"><SectionHeader title="Correlated provider signals" description="One incident—not three disconnected alerts" /><div className="mt-4 space-y-3">{signals.map((s) => <div key={s.source} className="flex gap-3 rounded-xl border border-eoc-border bg-white/[0.02] p-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-eoc-accent/10"><s.icon className="h-4 w-4 text-eoc-accent" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium text-eoc-fg">{s.source}</p><StatusPill tone={s.tone}>{s.time}</StatusPill></div><p className="mt-1 text-sm text-eoc-fg2">{s.title}</p><p className="mt-1 text-xs text-eoc-muted">{s.detail}</p></div></div>)}</div></Surface><Surface className="p-5"><SectionHeader title="Business impact" /><div className="mt-4 space-y-4"><Metric label="Checkout success" before="99.4%" now={phase === "verified" ? "99.6%" : "91.3%"} bad={phase !== "verified"} /><Metric label="p95 latency" before="224 ms" now={phase === "verified" ? "218 ms" : "1,840 ms"} bad={phase !== "verified"} /><Metric label="API error rate" before="0.3%" now={phase === "verified" ? "0.2%" : "8.7%"} bad={phase !== "verified"} /></div></Surface></div>
    {current >= 1 && <Surface className="border-eoc-accent/30 p-5"><div className="flex gap-3"><Sparkles className="mt-0.5 h-5 w-5 shrink-0 text-eoc-accent" /><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-eoc-fg">Correlated root-cause analysis</h3><StatusPill tone="success">High confidence</StatusPill></div><p className="mt-2 text-sm leading-6 text-eoc-fg2">Deployment <span className="font-mono text-eoc-fg">checkout-api v2.14.0</span> introduced an unindexed order lookup. Atlas began scanning 184k documents per request, saturating the API host CPU and increasing checkout latency.</p><p className="mt-2 text-xs text-eoc-muted">Evidence: deployment diff · query profiler · host metrics · dependency graph</p></div></div></Surface>}
    {current >= 2 && <Surface className="p-5"><SectionHeader title="Remediation plan" description="Policy-checked, reversible, and approval controlled" /><div className="mt-4 grid gap-4 lg:grid-cols-3"><PlanStep n="01" title="Rollback application" detail="Restore checkout-api v2.13.4 using the last verified image." /><PlanStep n="02" title="Verify recovery" detail="Run checkout synthetic tests and watch Atlas and host metrics for 2 minutes." /><PlanStep n="03" title="Prevent recurrence" detail="Open a patch task for the missing index and attach this evidence." /></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-eoc-border bg-white/[0.02] p-4"><div className="flex items-center gap-3"><RotateCcw className="h-5 w-5 text-eoc-accent" /><div><p className="text-sm font-medium text-eoc-fg">Risk: low · Estimated recovery: 3 minutes</p><p className="text-xs text-eoc-muted">No schema change · rollback image verified · automatic abort if health checks fail</p></div></div>{phase === "awaiting_approval" && <EButton variant="primary" disabled={busy} onClick={() => move("remediating", "Approval recorded. Executing rollback…", 1000)}><ShieldCheck className="h-4 w-4" /> Approve & execute</EButton>}{phase === "remediating" && <EButton variant="primary" disabled={busy} onClick={() => move("verified", "Running synthetic checks and verifying recovery…", 1200)}><Activity className="h-4 w-4" /> Verify recovery</EButton>}{phase === "verified" && <StatusPill tone="success">Recovery verified</StatusPill>}</div></Surface>}
    <div className="grid gap-4 lg:grid-cols-3"><Surface className="p-5 lg:col-span-2"><SectionHeader title="Immutable activity trail" description="Every automated and human action retained as evidence" /><ol className="mt-4 space-y-3">{trail[phase].map((item, i) => <li key={item} className="flex gap-3 text-sm"><CircleDot className={cn("mt-0.5 h-4 w-4 shrink-0", i === trail[phase].length - 1 ? "text-eoc-accent" : "text-eoc-success")} /><span className="text-eoc-fg2">{item}</span></li>)}</ol></Surface><Surface className="flex flex-col justify-between p-5"><div><SectionHeader title="Next action" /><p className="mt-3 text-sm leading-6 text-eoc-fg2">{phase === "detected" ? "Correlate telemetry and identify the most likely root cause." : phase === "investigating" ? "Generate a safe remediation plan and request approval." : phase === "awaiting_approval" ? "A production owner must approve before IAETDS changes infrastructure." : phase === "remediating" ? "Rollback is complete. Verify customer journeys and provider metrics." : "Incident is resolved. Export the evidence package for audit and review."}</p></div><div className="mt-5">{phase === "detected" && <EButton variant="primary" className="w-full" disabled={busy} onClick={() => move("investigating", "Correlating provider telemetry…")}><Sparkles className="h-4 w-4" /> Investigate signals</EButton>}{phase === "investigating" && <EButton variant="primary" className="w-full" disabled={busy} onClick={() => move("awaiting_approval", "Generating policy-checked remediation plan…")}><Play className="h-4 w-4" /> Build remediation plan</EButton>}{phase === "awaiting_approval" && <p className="text-xs text-eoc-muted">Approval control is shown in the remediation plan above.</p>}{phase === "remediating" && <p className="text-xs text-eoc-muted">Verification control is shown in the remediation plan above.</p>}{phase === "verified" && <EButton variant="secondary" className="w-full" onClick={exportEvidence}><Download className="h-4 w-4" /> Download evidence</EButton>}</div></Surface></div>
  </div>;
}
function Metric({ label, before, now, bad }: { label: string; before: string; now: string; bad: boolean }) { return <div className="flex items-end justify-between border-b border-eoc-border pb-3"><div><p className="text-xs text-eoc-muted">{label}</p><p className="mt-1 text-xs text-eoc-muted">Baseline {before}</p></div><p className={cn("text-lg font-semibold", bad ? "text-eoc-danger" : "text-eoc-success")}>{now}</p></div>; }
function PlanStep({ n, title, detail }: { n: string; title: string; detail: string }) { return <div className="rounded-xl border border-eoc-border bg-white/[0.02] p-4"><p className="font-mono text-xs text-eoc-accent">{n}</p><p className="mt-2 text-sm font-medium text-eoc-fg">{title}</p><p className="mt-1 text-xs leading-5 text-eoc-muted">{detail}</p></div>; }
