"use client";
import * as React from "react";
import { Download, Search } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { PageHeader, EButton } from "@/components/eoc/page-header";
import { SectionHeader, StatusPill, Surface, type Tone } from "@/components/eoc/primitives";
import { api } from "@/lib/api";
import { downloadText } from "@/lib/eoc/export";

type Audit={_id:string;action:string;actorEmail?:string;actorRole?:string;method?:string;path?:string;statusCode?:number;ip?:string;createdAt:string};
const tone=(action:string):Tone=>action.startsWith('auth.')?'info':action.includes('delete')?'danger':action.includes('security')?'warning':'neutral';
export default function AuditPage(){
 const [query,setQuery]=React.useState(""); const logs=useQuery<Audit[]>({queryKey:['audit-logs'],queryFn:async()=>{const {data}=await api.get('/audit-logs',{params:{limit:200}});return data.data}}); const rows=(logs.data||[]).filter(x=>!query||`${x.actorEmail} ${x.action} ${x.path}`.toLowerCase().includes(query.toLowerCase()));
 const exportLogs=()=>downloadText(`audit-logs-${Date.now()}.csv`,['time,actor,role,action,method,path,status,ip',...rows.map(x=>[x.createdAt,x.actorEmail,x.actorRole,x.action,x.method,x.path,x.statusCode,x.ip].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','))].join('\n'),'text/csv');
 return <div className="space-y-6"><PageHeader eyebrow="Compliance & governance" title="Audit Logs" description="Tenant-scoped records produced by real authentication, configuration, provisioning, asset and report actions." actions={<EButton variant="secondary" onClick={exportLogs} disabled={!rows.length}><Download/>Export logs</EButton>}/><div className="flex h-10 items-center gap-2 rounded-xl border border-eoc-border bg-white px-3"><Search className="h-4 w-4 text-eoc-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search actor, action or path…" className="flex-1 bg-transparent text-sm outline-none"/></div><Surface className="p-5"><SectionHeader title="Event timeline" description={`${rows.length} verified events`}/><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px]"><thead><tr className="text-left text-[11px] uppercase tracking-wide text-eoc-muted"><th className="pb-3">Time</th><th className="pb-3">Actor</th><th className="pb-3">Action</th><th className="pb-3">Request</th><th className="pb-3">Status</th><th className="pb-3">Source IP</th></tr></thead><tbody>{logs.isLoading?<tr><td colSpan={6} className="py-8 text-center text-sm text-eoc-muted">Loading audit evidence…</td></tr>:rows.length===0?<tr><td colSpan={6} className="py-8 text-center text-sm text-eoc-muted">No real audit events found.</td></tr>:rows.map(x=><tr key={x._id} className="border-t border-eoc-border text-sm"><td className="py-3 pr-4 text-xs text-eoc-muted">{new Date(x.createdAt).toLocaleString('en-IN')}</td><td className="py-3 pr-4"><p className="text-eoc-fg">{x.actorEmail||'System'}</p><p className="text-xs text-eoc-muted">{x.actorRole||'service'}</p></td><td className="py-3 pr-4"><StatusPill tone={tone(x.action)}>{x.action}</StatusPill></td><td className="py-3 pr-4 font-mono text-xs">{x.method} {x.path}</td><td className="py-3 pr-4">{x.statusCode||'—'}</td><td className="py-3 font-mono text-xs text-eoc-muted">{x.ip||'—'}</td></tr>)}</tbody></table></div></Surface></div>
}
